# Generated by Django 6.0.4 on 2026-04-22 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_account_balance_check_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="role_tags",
        ),
    ]
