# Generated by Django 6.0.4 on 2026-04-27 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_account_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="roundup_increment",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(5, "5"), (10, "10"), (20, "20"), (50, "50"), (100, "100")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="roundup_target_account",
            field=models.ForeignKey(
                blank=True,
                db_column="roundup_target_account_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roundup_sources",
                to="accounts.account",
            ),
        ),
    ]
