# Generated by Django 6.0.4 on 2026-04-27 15:57

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_account_roundup_increment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.JSONField(default=dict)),
                ("short_name", models.CharField(max_length=20)),
                ("svg_path", models.CharField(blank=True, default="", max_length=200)),
                ("brand_color", models.CharField(blank=True, default="", max_length=7)),
                ("country", models.CharField(default="EG", max_length=2)),
                (
                    "bank_type",
                    models.CharField(
                        choices=[
                            ("bank", "Bank"),
                            ("fintech", "Fintech"),
                            ("wallet", "Wallet"),
                        ],
                        default="bank",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
            ],
            options={
                "db_table": "system_banks",
                "ordering": ["display_order", "short_name"],
            },
        ),
    ]
