# Generated by Django 6.0.4 on 2026-04-27 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_seed_egypt_system_banks"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="system_bank",
            field=models.ForeignKey(
                blank=True,
                db_column="system_bank_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="institutions",
                to="accounts.systembank",
            ),
        ),
    ]
