# Generated by Django 6.0.4 on 2026-04-26 23:48

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "auth_app",
            "0009_remove_dailysnapshot_daily_snapshots_user_date_unique_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FeePreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="gen_random_uuid"),
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("currency", models.CharField(max_length=3)),
                (
                    "calc_type",
                    models.CharField(
                        choices=[("flat", "Flat"), ("percent", "Percent")],
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "min_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("archived", models.BooleanField(db_default=False, default=False)),
                ("sort_order", models.IntegerField(db_default=0, default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_app.user",
                    ),
                ),
            ],
            options={
                "db_table": "fee_presets",
                "unique_together": {("user", "name", "currency")},
            },
        ),
    ]
