# Generated by Django 6.0.4 on 2026-04-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0003_budget_max_rollover_budget_rollover_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="currency",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="totalbudget",
            name="currency",
            field=models.CharField(max_length=3),
        ),
    ]
