# Generated by Django 6.0.3 on 2026-04-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0003_state_only_daily_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(default="en", max_length=5),
        ),
    ]
