# Generated by Django 6.0.3 on 2026-04-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0004_add_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ar", "Arabic")],
                default="en",
                max_length=5,
            ),
        ),
    ]
