# Generated by Django 6.0.4 on 2026-04-22 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0005_alter_user_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userconfig",
            name="failed_attempts",
        ),
        migrations.RemoveField(
            model_name="userconfig",
            name="locked_until",
        ),
        migrations.RemoveField(
            model_name="userconfig",
            name="pin_hash",
        ),
        migrations.RemoveField(
            model_name="userconfig",
            name="session_key",
        ),
    ]
