# Generated by Django 6.0.4 on 2026-04-22

from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Coalesce, Now


def seed_currencies_and_preferences(apps, schema_editor):
    Currency = apps.get_model("auth_app", "Currency")
    UserCurrencyPreference = apps.get_model("auth_app", "UserCurrencyPreference")
    User = apps.get_model("auth_app", "User")
    Account = apps.get_model("accounts", "Account")
    Budget = apps.get_model("budgets", "Budget")
    TotalBudget = apps.get_model("budgets", "TotalBudget")
    Investment = apps.get_model("investments", "Investment")
    Transaction = apps.get_model("transactions", "Transaction")

    supported = [
        ("EGP", "Egyptian Pound", "EGP", 0),
        ("USD", "US Dollar", "$", 1),
        ("EUR", "Euro", "EUR", 2),
        ("GBP", "British Pound", "GBP", 3),
        ("AED", "UAE Dirham", "AED", 4),
        ("SAR", "Saudi Riyal", "SAR", 5),
    ]
    for code, name, symbol, display_order in supported:
        Currency.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "symbol": symbol,
                "is_enabled": True,
                "display_order": display_order,
            },
        )

    supported_codes = {code for code, *_rest in supported}

    for user in User.objects.all().only("id"):
        codes: set[str] = set()
        for model in (Account, Budget, TotalBudget, Investment, Transaction):
            user_codes = model.objects.filter(user_id=user.id).values_list(
                "currency", flat=True
            )
            for code in user_codes:
                normalized = str(code or "").upper().strip()
                if normalized in supported_codes:
                    codes.add(normalized)
        active_codes = sorted(codes) if codes else ["EGP"]
        selected = "EGP" if "EGP" in active_codes else active_codes[0]
        UserCurrencyPreference.objects.update_or_create(
            user_id=user.id,
            defaults={
                "active_currency_codes": active_codes,
                "selected_display_currency": selected,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0006_remove_userconfig_failed_attempts_and_more"),
        ("accounts", "0007_remove_account_role_tags"),
        ("budgets", "0003_budget_max_rollover_budget_rollover_enabled"),
        ("investments", "0002_retarget_user_fk"),
        ("transactions", "0008_remove_fee_amount_fee_account_from_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("code", models.CharField(max_length=3, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("symbol", models.CharField(blank=True, default="", max_length=8)),
                ("is_enabled", models.BooleanField(db_default=True, default=True)),
                ("display_order", models.IntegerField(db_default=0, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_default=Now())),
                ("updated_at", models.DateTimeField(auto_now=True, db_default=Now())),
            ],
            options={
                "db_table": "currencies",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="UserCurrencyPreference",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=models.deletion.CASCADE,
                        primary_key=True,
                        related_name="currency_preferences",
                        serialize=False,
                        to="auth_app.user",
                    ),
                ),
                ("active_currency_codes", models.JSONField(db_default="[]", default=list)),
                (
                    "selected_display_currency",
                    models.CharField(db_default="EGP", default="EGP", max_length=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_default=Now())),
                ("updated_at", models.DateTimeField(auto_now=True, db_default=Now())),
            ],
            options={
                "db_table": "user_currency_preferences",
            },
        ),
        migrations.RunPython(
            seed_currencies_and_preferences, migrations.RunPython.noop
        ),
    ]
