# Generated by Django 6.0.4 on 2026-04-23 21:02

import uuid
from collections import defaultdict
from decimal import Decimal
from typing import Any

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models
from django.utils import timezone

ZERO = Decimal("0")


def backfill_historical_snapshots(apps: Any, schema_editor: Any) -> None:
    Account = apps.get_model("accounts", "Account")
    AccountSnapshot = apps.get_model("accounts", "AccountSnapshot")
    DailySnapshot = apps.get_model("auth_app", "DailySnapshot")
    HistoricalSnapshot = apps.get_model("auth_app", "HistoricalSnapshot")
    Transaction = apps.get_model("transactions", "Transaction")
    VirtualAccount = apps.get_model("virtual_accounts", "VirtualAccount")

    totals_by_user_date: dict[tuple[Any, Any], dict[str, Decimal]] = defaultdict(
        lambda: defaultdict(lambda: ZERO)
    )
    spending_by_user_date: dict[tuple[Any, Any], dict[str, Decimal]] = defaultdict(
        lambda: defaultdict(lambda: ZERO)
    )
    income_by_user_date: dict[tuple[Any, Any], dict[str, Decimal]] = defaultdict(
        lambda: defaultdict(lambda: ZERO)
    )

    for (
        user_id,
        snapshot_date,
        currency,
        balance,
    ) in AccountSnapshot.objects.select_related("account").values_list(
        "user_id", "date", "account__currency", "balance"
    ):
        totals_by_user_date[(user_id, snapshot_date)][currency] += balance

    today = timezone.now().date()
    for user_id, currency, balance in Account.objects.filter(
        is_dormant=False
    ).values_list("user_id", "currency", "current_balance"):
        totals_by_user_date[(user_id, today)][currency] += balance

    for user_id, balance in VirtualAccount.objects.filter(
        exclude_from_net_worth=True,
        is_archived=False,
    ).values_list("user_id", "current_balance"):
        totals_by_user_date[(user_id, today)]["EGP"] -= balance

    for user_id, tx_date, currency, tx_type, amount in Transaction.objects.values_list(
        "user_id", "date", "currency", "type", "amount"
    ):
        key = (user_id, tx_date)
        if tx_type == "expense":
            spending_by_user_date[key][currency] += amount
        elif tx_type == "income":
            income_by_user_date[key][currency] += amount

    fallback_daily_rows = DailySnapshot.objects.values_list(
        "user_id", "date", "net_worth_egp", "daily_spending", "daily_income"
    )

    for (
        user_id,
        snapshot_date,
        net_worth_egp,
        daily_spending,
        daily_income,
    ) in fallback_daily_rows:
        key = (user_id, snapshot_date)
        if key in totals_by_user_date:
            continue
        totals_by_user_date[key]["EGP"] = net_worth_egp
        if daily_spending:
            spending_by_user_date[key]["EGP"] = daily_spending
        if daily_income:
            income_by_user_date[key]["EGP"] = daily_income

    all_keys = {
        *totals_by_user_date.keys(),
        *spending_by_user_date.keys(),
        *income_by_user_date.keys(),
    }

    for user_id, snapshot_date in all_keys:
        totals = totals_by_user_date.get((user_id, snapshot_date), {})
        spending = spending_by_user_date.get((user_id, snapshot_date), {})
        income = income_by_user_date.get((user_id, snapshot_date), {})
        currencies = {*totals.keys(), *spending.keys(), *income.keys()}
        for currency in currencies:
            HistoricalSnapshot.objects.update_or_create(
                user_id=user_id,
                date=snapshot_date,
                currency=currency,
                defaults={
                    "net_worth": totals.get(currency, ZERO),
                    "daily_spending": spending.get(currency, ZERO),
                    "daily_income": income.get(currency, ZERO),
                },
            )


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0007_currency_registry_and_preferences"),
        ("accounts", "0007_remove_account_role_tags"),
        ("transactions", "0008_remove_fee_amount_fee_account_from_transaction"),
        ("virtual_accounts", "0004_add_savings_goals"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="gen_random_uuid"),
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("currency", models.CharField(db_index=True, max_length=3)),
                (
                    "net_worth",
                    models.DecimalField(db_default=0, decimal_places=2, max_digits=15),
                ),
                (
                    "daily_spending",
                    models.DecimalField(
                        db_default=0, decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "daily_income",
                    models.DecimalField(
                        db_default=0, decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_app.user",
                    ),
                ),
            ],
            options={
                "db_table": "historical_snapshots",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date", "currency"),
                        name="historical_snapshots_user_date_currency_unique",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_historical_snapshots, migrations.RunPython.noop),
    ]
