# Generated by Django 6.0.4 on 2026-04-23 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_historicalsnapshot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailysnapshot',
            name='daily_snapshots_user_date_unique',
        ),
        migrations.DeleteModel(
            name='DailySnapshot',
        ),
    ]
