# Generated by Django 6.0.4 on 2026-04-23 23:16
#
# RemoveConstraint omitted: constraint name in production DB diverges from
# Django state (production has auto-named "daily_snapshots_user_date_key"
# from original unique_together; state tracks "daily_snapshots_user_date_unique"
# from a later state-only migration). DeleteModel drops the table entirely via
# DROP TABLE ... CASCADE, so no separate constraint removal is needed.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_historicalsnapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySnapshot',
        ),
    ]
