# Generated by Django 6.0.4 on 2026-04-23 23:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0003_personcurrencybalance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="net_balance",
        ),
        migrations.RemoveField(
            model_name="person",
            name="net_balance_egp",
        ),
        migrations.RemoveField(
            model_name="person",
            name="net_balance_usd",
        ),
    ]
