# Generated by Django 6.0.3 on 2026-04-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0005_rename_name_json_to_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.JSONField(default=dict),
        ),
    ]
