-- =============================================================================
-- Migration 000017: Add Account Health Config (JSONB)
-- =============================================================================
--
-- TASK-068: Account health constraints — minimum balance and minimum monthly deposit.
--
-- JSONB FOR FLEXIBLE CONFIGURATION
-- -----------------------------------
-- Instead of adding separate columns (min_balance NUMERIC, min_monthly_deposit NUMERIC),
-- we use a single JSONB column. This is the "schema-less" or "document" approach.
--
-- Example value:
--   {"min_balance": 5000, "min_monthly_deposit": 1000}
--
-- Why JSONB instead of separate columns?
--   1. Extensibility: Adding new health rules (e.g., "max_withdrawal_per_day", "target_balance")
--      requires NO migration — just start storing the new key in the JSON.
--      With columns, each new rule needs ALTER TABLE ADD COLUMN + a new migration.
--
--   2. Sparseness: Most accounts won't have health rules. With separate columns,
--      you'd have many NULL columns. With JSONB, accounts without health rules
--      simply have health_config = NULL (one column instead of many).
--
--   3. Flexibility: Different account types might have different health rules.
--      Credit cards might track "min_payment_day", savings might track "min_balance."
--      JSONB handles this naturally without a rigid column structure.
--
-- Trade-offs:
--   - No type safety: the DB doesn't enforce that min_balance is a number.
--     The application layer must validate the JSON structure.
--   - No NOT NULL on individual fields: can't require min_balance at DB level.
--   - Query syntax is different: WHERE health_config->>'min_balance' vs WHERE min_balance
--
-- When to use JSONB vs separate columns:
--   JSONB: optional, sparse, evolving data with varying structure per row
--   Columns: required, consistent data that every row has, needs DB-level validation
--
-- QUERYING JSONB
-- ----------------
-- PostgreSQL provides operators to query inside JSONB:
--   ->   : get JSON object field (returns JSON)
--   ->>  : get JSON object field (returns TEXT)
--   @>   : contains (for filtering)
--
-- Examples:
--   SELECT * FROM accounts WHERE health_config->>'min_balance' IS NOT NULL;
--   SELECT * FROM accounts WHERE (health_config->>'min_balance')::numeric > 0;
--   SELECT * FROM accounts WHERE health_config @> '{"min_balance": 5000}';
--
-- Laravel:
--   $table->jsonb('health_config')->nullable();
--   // Query: Account::whereJsonContains('health_config->min_balance', 5000)->get();
--   // Or:   Account::whereNotNull('health_config->min_balance')->get();
--
-- Django:
--   health_config = models.JSONField(null=True, blank=True)
--   // Query: Account.objects.filter(health_config__min_balance__gt=0)
--   // Django's JSONField ORM lookups are very powerful on PostgreSQL.
--
-- DEFAULT NULL vs DEFAULT '{}'
-- ------------------------------
-- We use DEFAULT NULL (not DEFAULT '{}') because NULL clearly means
-- "no health config set" — the account has no health rules.
-- An empty JSON object '{}' would mean "health config exists but has no rules,"
-- which is a subtly different semantic that could cause confusion.
--
-- ADD COLUMN IF NOT EXISTS
-- --------------------------
-- IF NOT EXISTS prevents an error if the column already exists. This makes
-- the migration idempotent — safe to run multiple times (though golang-migrate
-- tracks this, it's a good defensive practice).
--
-- Laravel: Schema::table('accounts', fn($t) => $t->jsonb('health_config')->nullable());
--          // Laravel doesn't have IF NOT EXISTS for columns — you'd check manually.
-- Django:  health_config = models.JSONField(null=True, default=None)
--          // Django migrations handle existence checks automatically.
--
-- Docs: https://www.postgresql.org/docs/current/datatype-json.html
--       https://www.postgresql.org/docs/current/functions-json.html
-- =============================================================================

-- TASK-068: Account health constraints — min balance and min monthly deposit.
-- Stored as JSONB to keep the schema flexible for future health rules.
-- Example: {"min_balance": 5000, "min_monthly_deposit": 1000}
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS health_config JSONB DEFAULT NULL;
