-- =============================================================================
-- Migration 000012: Add balance_delta Column to Transactions
-- =============================================================================
--
-- ALTER TABLE ... ADD COLUMN
-- ---------------------------
-- This is a schema migration that modifies an existing table (not creating a new one).
-- ALTER TABLE adds, removes, or modifies columns on a table that already has data.
--
-- Laravel: Schema::table('transactions', fn (Blueprint $table) => $table->decimal('balance_delta', 15, 2)->default(0));
-- Django:  Just add the field to the model and run `python manage.py makemigrations`
--          balance_delta = models.DecimalField(max_digits=15, decimal_places=2, default=0)
--
-- RECONCILIATION STRATEGY (balance_delta)
-- -----------------------------------------
-- The balance_delta column records the ACTUAL impact of each transaction on an account's
-- balance. This is the key to the reconciliation system.
--
-- How it works:
--   - expense:  balance_delta = -amount (reduces balance)
--   - income:   balance_delta = +amount (increases balance)
--   - transfer FROM: balance_delta = -amount (sender loses money)
--   - transfer TO:   balance_delta = +amount (receiver gains money)
--   - exchange: similar to transfer but with currency conversion
--
-- The reconciliation formula:
--   expected_balance = initial_balance + SUM(balance_delta) for all account transactions
--   If expected_balance ≠ current_balance, something is wrong → fix it.
--
-- This is similar to DOUBLE-ENTRY BOOKKEEPING in accounting:
--   Every transaction has a debit (negative delta) and credit (positive delta).
--   The sum of all deltas should equal the current balance minus the initial balance.
--
-- Why DEFAULT 0?
--   Existing transactions (created before this migration) get balance_delta = 0.
--   We can't retroactively compute the correct delta for old transfers/exchanges
--   because we'd need to know which side of the transfer this was.
--   Going forward, the application sets the correct delta on every new transaction.
--   The reconciliation job (make reconcile) can recalculate and fix these.
--
-- NOT NULL DEFAULT 0:
--   In PostgreSQL, adding a NOT NULL column with a DEFAULT to an existing table is
--   fast (since PG 11) — it doesn't rewrite every row. The default is stored in
--   the catalog metadata and applied lazily on read. This makes the migration
--   nearly instant even on large tables.
--
-- Docs: https://www.postgresql.org/docs/current/sql-altertable.html
-- =============================================================================

-- Add balance_delta column to transactions to store the actual balance impact.
-- This makes reconciliation straightforward: expected_balance = initial_balance + SUM(balance_delta).
-- For existing transactions, we can't retroactively determine the delta for transfers/exchanges,
-- so we leave them as 0 and only populate going forward.
ALTER TABLE transactions ADD COLUMN balance_delta NUMERIC(15,2) NOT NULL DEFAULT 0;
