# Generated by Django 6.0.4 on 2026-04-18 02:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("push", "0001_notification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notif_user_read_created_idx",
            old_name="notifications_user_read_created_idx",
        ),
    ]
