# Generated by Django 6.0.3 on 2026-04-16 03:11

from django.db import migrations


def migrate_tags(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')
    Tag = apps.get_model('transactions', 'Tag')

    # Process all transactions that have tags in the ArrayField
    for tx in Transaction.objects.exclude(tags=[]):
        for tag_name in tx.tags:
            tag_name = tag_name.strip()
            if not tag_name:
                continue

            # Get or create the tag for this user
            tag, _ = Tag.objects.get_or_create(
                user_id=tx.user_id,
                name=tag_name,
                defaults={'color': '#64748b'}
            )
            tx.transaction_tags.add(tag)

class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_tag_transaction_transaction_tags'),
    ]

    operations = [
        migrations.RunPython(migrate_tags, reverse_code=migrations.RunPython.noop),
    ]
