# Generated by Django 6.0.3 on 2026-04-16 03:11

from typing import Any

from django.db import migrations


def migrate_tags(apps: Any, schema_editor: Any) -> None:
    Transaction = apps.get_model("transactions", "Transaction")
    Tag = apps.get_model("transactions", "Tag")

    # Use raw SQL filter to avoid ORM type-cast mismatch (text[] vs varchar[])
    # on production. array_length returns NULL for empty arrays so > 0 is safe.
    for tx in Transaction.objects.extra(  # noqa: S610
        where=["array_length(tags, 1) > 0"]
    ):
        for tag_name in tx.tags:
            tag_name = tag_name.strip()
            if not tag_name:
                continue

            # Get or create the tag for this user
            tag, _ = Tag.objects.get_or_create(
                user_id=tx.user_id, name=tag_name, defaults={"color": "#64748b"}
            )
            tx.transaction_tags.add(tag)


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_tag_transaction_transaction_tags"),
    ]

    operations = [
        migrations.RunPython(migrate_tags, reverse_code=migrations.RunPython.noop),
    ]
