# Generated by Django 6.0.3 on 2026-04-16 03:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_migrate_array_tags_to_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="tags",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="transaction_tags",
            new_name="tags",
        ),
    ]
