# Generated by Django 6.0.3 on 2026-04-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0005_remove_transaction_transaction_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_verified",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
