# Generated by Django 6.0.3 on 2026-04-16 05:28

from django.db import migrations, models

import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=transactions.models.transaction_attachment_path),
        ),
    ]
