# Generated by Django 6.0.4 on 2026-04-17 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0007_transaction_attachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="fee_account",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="fee_amount",
        ),
    ]
