# Generated by Django 6.0.4 on 2026-04-27 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0010_transaction_account_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_roundup",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="parent_transaction",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_transaction_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roundup_children",
                to="transactions.transaction",
            ),
        ),
    ]
