# Generated by Django 6.0.4 on 2026-04-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0011_transaction_is_roundup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_pending",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="original_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
