# Generated by Django 6.0.3 on 2026-03-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailysnapshot",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
