# Generated by Django 6.0.3 on 2026-03-24 10:09

import uuid

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_drop_enums_convert_to_varchar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(db_default="EGP", max_length=3),
        ),
        migrations.AlterField(
            model_name="account",
            name="current_balance",
            field=models.DecimalField(
                db_default=0, decimal_places=2, default=0, max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="display_order",
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="initial_balance",
            field=models.DecimalField(
                db_default=0, decimal_places=2, default=0, max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_dormant",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="account",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="accountsnapshot",
            name="balance",
            field=models.DecimalField(db_default=0, decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="accountsnapshot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="accountsnapshot",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="authtoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="authtoken",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="authtoken",
            name="purpose",
            field=models.CharField(db_default="login", default="login", max_length=20),
        ),
        migrations.AlterField(
            model_name="authtoken",
            name="used",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="budget",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="currency",
            field=models.CharField(db_default="EGP", max_length=3),
        ),
        migrations.AlterField(
            model_name="budget",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="is_active",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name="budget",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="display_order",
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_archived",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_system",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="dailysnapshot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="dailysnapshot",
            name="daily_income",
            field=models.DecimalField(
                db_default=0, decimal_places=2, default=0, max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="dailysnapshot",
            name="daily_spending",
            field=models.DecimalField(
                db_default=0, decimal_places=2, default=0, max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="dailysnapshot",
            name="exchange_rate",
            field=models.DecimalField(db_default=0, decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="dailysnapshot",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="dailysnapshot",
            name="net_worth_egp",
            field=models.DecimalField(db_default=0, decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailysnapshot",
            name="net_worth_raw",
            field=models.DecimalField(db_default=0, decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="exchangeratelog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="exchangeratelog",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="display_order",
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name="institution",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="type",
            field=models.CharField(db_default="bank", max_length=20),
        ),
        migrations.AlterField(
            model_name="institution",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="currency",
            field=models.CharField(db_default="EGP", max_length=3),
        ),
        migrations.AlterField(
            model_name="investment",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="last_unit_price",
            field=models.DecimalField(db_default=0, decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="investment",
            name="last_updated",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="platform",
            field=models.CharField(db_default="Thndr", max_length=100),
        ),
        migrations.AlterField(
            model_name="investment",
            name="units",
            field=models.DecimalField(db_default=0, decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="investment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="net_balance",
            field=models.DecimalField(
                db_default=0, decimal_places=2, default=0, max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="net_balance_egp",
            field=models.DecimalField(
                db_default=0, decimal_places=2, default=0, max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="net_balance_usd",
            field=models.DecimalField(
                db_default=0, decimal_places=2, default=0, max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="recurringrule",
            name="auto_confirm",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="recurringrule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="recurringrule",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="recurringrule",
            name="is_active",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name="recurringrule",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="balance_delta",
            field=models.DecimalField(
                db_default=0, decimal_places=2, default=0, max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(
                db_default=django.db.models.functions.datetime.Now(), db_index=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="userconfig",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userconfig",
            name="failed_attempts",
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name="userconfig",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userconfig",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="virtualaccount",
            name="color",
            field=models.CharField(
                blank=True, db_default="#0d9488", default="", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="virtualaccount",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="virtualaccount",
            name="current_balance",
            field=models.DecimalField(
                db_default=0, decimal_places=2, default=0, max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="virtualaccount",
            name="display_order",
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name="virtualaccount",
            name="exclude_from_net_worth",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="virtualaccount",
            name="icon",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="virtualaccount",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="virtualaccount",
            name="is_archived",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="virtualaccount",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="virtualaccountallocation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="virtualaccountallocation",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="gen_random_uuid"),
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
            ),
        ),
        # --- RunSQL: array/JSON defaults that db_default can't express ---
        migrations.RunSQL(
            sql="""
            ALTER TABLE accounts ALTER COLUMN role_tags SET DEFAULT '{}'::text[];
            ALTER TABLE accounts ALTER COLUMN metadata SET DEFAULT '{}'::jsonb;
            ALTER TABLE transactions ALTER COLUMN tags SET DEFAULT '{}'::text[];
            """,
            reverse_sql="""
            ALTER TABLE accounts ALTER COLUMN role_tags DROP DEFAULT;
            ALTER TABLE accounts ALTER COLUMN metadata DROP DEFAULT;
            ALTER TABLE transactions ALTER COLUMN tags DROP DEFAULT;
            """,
        ),
        # --- RunSQL: convert text → varchar on production (no-op on fresh DBs) ---
        migrations.RunSQL(
            sql="""
            DO $$
            DECLARE
                cols TEXT[][] := ARRAY[
                    ['users', 'email', '255'],
                    ['sessions', 'token', '255'],
                    ['auth_tokens', 'email', '255'],
                    ['auth_tokens', 'token', '255'],
                    ['auth_tokens', 'purpose', '20'],
                    ['institutions', 'name', '255'],
                    ['institutions', 'icon', '255'],
                    ['institutions', 'color', '20'],
                    ['accounts', 'name', '100'],
                    ['categories', 'name', '100'],
                    ['categories', 'icon', '10'],
                    ['persons', 'name', '100'],
                    ['exchange_rate_log', 'source', '50']
                ];
            BEGIN
                FOR i IN 1..array_length(cols, 1) LOOP
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = cols[i][1]
                        AND column_name = cols[i][2]
                        AND data_type = 'text'
                    ) THEN
                        EXECUTE format(
                            'ALTER TABLE %I ALTER COLUMN %I TYPE varchar(%s)',
                            cols[i][1], cols[i][2], cols[i][3]
                        );
                    END IF;
                END LOOP;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # --- RunSQL: fix unique constraints (drop Go-era, Django's are in 0001) ---
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'account_snapshots_date_account_id_key'
                ) THEN
                    ALTER TABLE account_snapshots
                        DROP CONSTRAINT account_snapshots_date_account_id_key;
                END IF;
            END $$;

            DROP INDEX IF EXISTS idx_users_email_lower;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # --- RunSQL: drop Go-era schema_migrations table ---
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS schema_migrations;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
