# Generated by Django 6.0.3 on 2026-03-25 06:29

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_create_materialized_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="TotalBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="gen_random_uuid"),
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("monthly_limit", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(db_default="EGP", max_length=3)),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "total_budgets",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "currency"),
                        name="uq_total_budget_user_currency",
                    )
                ],
            },
        ),
    ]
